# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'context_editor_widget.ui'
#
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_ContextWidget(object):
    def setupUi(self, ContextWidget):
        ContextWidget.setObjectName("ContextWidget")
        ContextWidget.resize(399, 85)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ContextWidget.sizePolicy().hasHeightForWidth())
        ContextWidget.setSizePolicy(sizePolicy)
        ContextWidget.setMinimumSize(QtCore.QSize(0, 85))
        self.gridLayout = QtGui.QGridLayout(ContextWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 6)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.task_label = QtGui.QLabel(ContextWidget)
        self.task_label.setMinimumSize(QtCore.QSize(0, 0))
        self.task_label.setMaximumSize(QtCore.QSize(16777215, 32))
        self.task_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.task_label.setMargin(4)
        self.task_label.setOpenExternalLinks(True)
        self.task_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.task_label.setObjectName("task_label")
        self.gridLayout.addWidget(self.task_label, 0, 0, 1, 1)
        self.task_widgets_layout = QtGui.QHBoxLayout()
        self.task_widgets_layout.setSpacing(2)
        self.task_widgets_layout.setObjectName("task_widgets_layout")
        self.task_display = QtGui.QLabel(ContextWidget)
        self.task_display.setMinimumSize(QtCore.QSize(0, 0))
        self.task_display.setMaximumSize(QtCore.QSize(16777215, 32))
        self.task_display.setMargin(4)
        self.task_display.setOpenExternalLinks(True)
        self.task_display.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.task_display.setObjectName("task_display")
        self.task_widgets_layout.addWidget(self.task_display)
        self.task_search_layout = QtGui.QHBoxLayout()
        self.task_search_layout.setSpacing(0)
        self.task_search_layout.setObjectName("task_search_layout")
        self.task_search = GlobalSearchWidget(ContextWidget)
        self.task_search.setMinimumSize(QtCore.QSize(0, 32))
        self.task_search.setMaximumSize(QtCore.QSize(16777215, 32))
        self.task_search.setObjectName("task_search")
        self.task_search_layout.addWidget(self.task_search)
        self.task_menu_btn = QtGui.QToolButton(ContextWidget)
        self.task_menu_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.task_menu_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.task_menu_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.task_menu_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.task_menu_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/tk_multi_publish2/down_arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.task_menu_btn.setIcon(icon)
        self.task_menu_btn.setIconSize(QtCore.QSize(32, 32))
        self.task_menu_btn.setCheckable(False)
        self.task_menu_btn.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.task_menu_btn.setObjectName("task_menu_btn")
        self.task_search_layout.addWidget(self.task_menu_btn)
        self.task_widgets_layout.addLayout(self.task_search_layout)
        self.task_search_btn = QtGui.QToolButton(ContextWidget)
        self.task_search_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.task_search_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.task_search_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/tk_multi_publish2/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.task_search_btn.setIcon(icon1)
        self.task_search_btn.setIconSize(QtCore.QSize(32, 32))
        self.task_search_btn.setCheckable(True)
        self.task_search_btn.setObjectName("task_search_btn")
        self.task_widgets_layout.addWidget(self.task_search_btn)
        self.task_widgets_layout.setStretch(0, 4)
        self.task_widgets_layout.setStretch(1, 4)
        self.task_widgets_layout.setStretch(2, 1)
        self.gridLayout.addLayout(self.task_widgets_layout, 0, 1, 1, 1)
        self.link_label = QtGui.QLabel(ContextWidget)
        self.link_label.setMinimumSize(QtCore.QSize(0, 0))
        self.link_label.setMaximumSize(QtCore.QSize(16777215, 32))
        self.link_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.link_label.setMargin(4)
        self.link_label.setOpenExternalLinks(True)
        self.link_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.link_label.setObjectName("link_label")
        self.gridLayout.addWidget(self.link_label, 1, 0, 1, 1)
        self.link_widgets_layout = QtGui.QHBoxLayout()
        self.link_widgets_layout.setSpacing(2)
        self.link_widgets_layout.setObjectName("link_widgets_layout")
        self.link_display = QtGui.QLabel(ContextWidget)
        self.link_display.setMinimumSize(QtCore.QSize(0, 0))
        self.link_display.setMaximumSize(QtCore.QSize(16777215, 32))
        self.link_display.setMargin(4)
        self.link_display.setOpenExternalLinks(True)
        self.link_display.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.link_display.setObjectName("link_display")
        self.link_widgets_layout.addWidget(self.link_display)
        self.link_search = GlobalSearchWidget(ContextWidget)
        self.link_search.setMinimumSize(QtCore.QSize(0, 32))
        self.link_search.setMaximumSize(QtCore.QSize(16777215, 32))
        self.link_search.setObjectName("link_search")
        self.link_widgets_layout.addWidget(self.link_search)
        self.link_search_btn = QtGui.QToolButton(ContextWidget)
        self.link_search_btn.setMinimumSize(QtCore.QSize(32, 32))
        self.link_search_btn.setMaximumSize(QtCore.QSize(32, 32))
        self.link_search_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.link_search_btn.setIcon(icon1)
        self.link_search_btn.setIconSize(QtCore.QSize(32, 32))
        self.link_search_btn.setCheckable(True)
        self.link_search_btn.setObjectName("link_search_btn")
        self.link_widgets_layout.addWidget(self.link_search_btn)
        self.link_widgets_layout.setStretch(0, 4)
        self.link_widgets_layout.setStretch(1, 4)
        self.link_widgets_layout.setStretch(2, 1)
        self.gridLayout.addLayout(self.link_widgets_layout, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 10)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)

        self.retranslateUi(ContextWidget)
        QtCore.QMetaObject.connectSlotsByName(ContextWidget)

    def retranslateUi(self, ContextWidget):
        ContextWidget.setWindowTitle(QtGui.QApplication.translate("ContextWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.task_label.setToolTip(QtGui.QApplication.translate("ContextWidget", "<html><head/><body><p>The context for the currently selected item on the left. Click the name to go to that context in Shotgun.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.task_label.setText(QtGui.QApplication.translate("ContextWidget", "Task: ", None, QtGui.QApplication.UnicodeUTF8))
        self.task_display.setToolTip(QtGui.QApplication.translate("ContextWidget", "<html><head/><body><p>The context for the currently selected item on the left. Click the name to go to that context in Shotgun.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.task_display.setText(QtGui.QApplication.translate("ContextWidget", "Loading...", None, QtGui.QApplication.UnicodeUTF8))
        self.task_search.setToolTip(QtGui.QApplication.translate("ContextWidget", "<html><head/><body><p>Type in this box to find a Shotgun entity or task to associate with the currently selected item to publish.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.task_menu_btn.setToolTip(QtGui.QApplication.translate("ContextWidget", "<html><head/><body><p>Show a menu for recently used contexts and tasks assigned to you. </p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.task_search_btn.setToolTip(QtGui.QApplication.translate("ContextWidget", "<html><head/><body><p>Toggle this button to allow searching for a context to link to the selected publish item.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.task_search_btn.setText(QtGui.QApplication.translate("ContextWidget", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.link_label.setToolTip(QtGui.QApplication.translate("ContextWidget", "<html><head/><body><p>The context for the currently selected item on the left. Click the name to go to that context in Shotgun.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.link_label.setText(QtGui.QApplication.translate("ContextWidget", "Link: ", None, QtGui.QApplication.UnicodeUTF8))
        self.link_display.setToolTip(QtGui.QApplication.translate("ContextWidget", "<html><head/><body><p>The context for the currently selected item on the left. Click the name to go to that context in Shotgun.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.link_display.setText(QtGui.QApplication.translate("ContextWidget", "Loading...", None, QtGui.QApplication.UnicodeUTF8))
        self.link_search.setToolTip(QtGui.QApplication.translate("ContextWidget", "<html><head/><body><p>Type in this box to find a Shotgun entity or task to associate with the currently selected item to publish.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.link_search_btn.setToolTip(QtGui.QApplication.translate("ContextWidget", "<html><head/><body><p>Toggle this button to allow searching for a context to link to the selected publish item.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.link_search_btn.setText(QtGui.QApplication.translate("ContextWidget", "...", None, QtGui.QApplication.UnicodeUTF8))

from ..qtwidgets import GlobalSearchWidget
from . import resources_rc
