# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'publish_details.ui'
#
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_PublishDetails(object):
    def setupUi(self, PublishDetails):
        PublishDetails.setObjectName("PublishDetails")
        PublishDetails.resize(288, 513)
        self.verticalLayout = QtGui.QVBoxLayout(PublishDetails)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.details_scroll = QtGui.QScrollArea(PublishDetails)
        self.details_scroll.setWidgetResizable(True)
        self.details_scroll.setObjectName("details_scroll")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 286, 511))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.header_context = QtGui.QLabel(self.frame)
        self.header_context.setWordWrap(True)
        self.header_context.setObjectName("header_context")
        self.verticalLayout_3.addWidget(self.header_context)
        self.label_12 = QtGui.QLabel(self.frame)
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_3.addWidget(self.label_12)
        self.header_thumbnail = QtGui.QLabel(self.frame)
        self.header_thumbnail.setWordWrap(True)
        self.header_thumbnail.setObjectName("header_thumbnail")
        self.verticalLayout_3.addWidget(self.header_thumbnail)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.thumbnail = QtGui.QLabel(self.frame)
        self.thumbnail.setMinimumSize(QtCore.QSize(100, 80))
        self.thumbnail.setMaximumSize(QtCore.QSize(100, 80))
        self.thumbnail.setText("")
        self.thumbnail.setPixmap(QtGui.QPixmap(":/tk_multi_publish2/screenshot.png"))
        self.thumbnail.setScaledContents(True)
        self.thumbnail.setObjectName("thumbnail")
        self.horizontalLayout_3.addWidget(self.thumbnail)
        self.label_11 = QtGui.QLabel(self.frame)
        self.label_11.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_11.setWordWrap(True)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.header_description = QtGui.QLabel(self.frame)
        self.header_description.setWordWrap(True)
        self.header_description.setObjectName("header_description")
        self.verticalLayout_3.addWidget(self.header_description)
        self.label_10 = QtGui.QLabel(self.frame)
        self.label_10.setWordWrap(True)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 120))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout_3.addWidget(self.plainTextEdit)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.frame)
        self.details_scroll.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.details_scroll)

        self.retranslateUi(PublishDetails)
        QtCore.QMetaObject.connectSlotsByName(PublishDetails)

    def retranslateUi(self, PublishDetails):
        PublishDetails.setWindowTitle(QtGui.QApplication.translate("PublishDetails", "Details", None, QtGui.QApplication.UnicodeUTF8))
        self.header_context.setText(QtGui.QApplication.translate("PublishDetails", "Shotgun Association", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("PublishDetails", "Your publish will be associated with the following shotgun item:", None, QtGui.QApplication.UnicodeUTF8))
        self.header_thumbnail.setText(QtGui.QApplication.translate("PublishDetails", "Thumbnail", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("PublishDetails", "You can associate a screenshot with your publish", None, QtGui.QApplication.UnicodeUTF8))
        self.header_description.setText(QtGui.QApplication.translate("PublishDetails", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("PublishDetails", "Please enter a short description to summarize your changes.", None, QtGui.QApplication.UnicodeUTF8))

from . import resources_rc
